{
    "ko": [
        {
            "text": "These utilities are really just a shortcut for adding margin to all-but-the-first-item in a group, and aren’t designed to handle complex cases like grids, layouts that wrap, or situations where the children are rendered in a complex custom order rather than their natural DOM order.",
            "timestamp": 1632902515,
            "email": null
        }
    ]
}