{
    "language": "en",
    "text": "Laravel Tinker is a powerful REPL for the Laravel framework, powered by the [PsySH](https:\/\/github.com\/bobthecow\/psysh) package.",
    "key": "7d\\1a\\7b\\40\\00\\3c\\a5\\92",
    "ko": [
        {
            "text": "라라벨 Tinker는 [PsySH](https:\/\/github.com\/bobthecow\/psysh) 패키지로 구동되는 Laravel 프레임워크를 위한 강력한 REPL입니다.",
            "timestamp": 1634285261,
            "email": null,
            "default": null
        }
    ]
}