{
    "language": "en",
    "text": "In addition to the commands provided with Artisan, you may build your own custom commands. Commands are typically stored in the `app\/Console\/Commands` directory; however, you are free to choose your own storage location as long as your commands can be loaded by Composer.",
    "key": "ae\\f9\\de\\55\\0e\\e3\\69\\a4",
    "ko": [
        {
            "text": "아티즌에서 제공하는 명령어들 외에에도 원하는 명령어를 만들 수 있습니다. 일반적으로 명령어는 `app\/Console\/Commands` 디렉토리에 저장하지만, 컴포저를 이용하여 커맨드를 로드할 수만 있다면 다른 원하는 위치에 저장해도 상관없습니다.",
            "timestamp": 1634285363,
            "email": null,
            "default": null
        }
    ]
}