{
    "language": "en",
    "text": "Artisan is the command line interface included with Laravel. Artisan exists at the root of your application as the `artisan` script and provides a number of helpful commands that can assist you while you build your application. To view a list of all available Artisan commands, you may use the `list` command:",
    "key": "f4\\ff\\c3\\df\\99\\4f\\a0\\4a",
    "ko": [
        {
            "text": "아티즌(Artisan)은 라라벨에 포함된 커맨드라인 인터페이스(CLI)의 이름입니다. Artisan은 `artisan` 스크립트 파일로 애플리케이션의 최상위 폴더에 존재하며 애플리케이션을 빌드하는 동안 도움이 될 수있는 여러가지 유용한 명령을 제공합니다. 실행가능한 아티즌 명령어 목록을 확인하려면 `list` 명령어를 다음과 같이 입력하면 됩니다.",
            "timestamp": 1634285002,
            "email": null,
            "default": null
        }
    ]
}