{
    "language": "en",
    "text": "All Laravel applications include Tinker by default. However, you may install Tinker using Composer if you have previously removed it from your application:",
    "key": "b9\\57\\72\\69\\e8\\ad\\9f\\68",
    "ko": [
        {
            "text": "모든 라라벨 애플리케이션은 기본적으로 Tinker를 포함합니다. 이전에 애플리케이션에서 Tinker를 삭제했을 경우 Composer를 사용하여 Tinker를 다시 설치할 수 있습니다.",
            "timestamp": 1634285280,
            "email": null,
            "default": null
        }
    ]
}