{
    "language": "en",
    "text": "> {tip} For greater code reuse, it is good practice to keep your console commands light and let them defer to application services to accomplish their tasks. In the example above, note that we inject a service class to do the \"heavy lifting\" of sending the e-mails.",
    "key": "f6\\bf\\58\\47\\03\\a1\\56\\1e",
    "ko": [
        {
            "text": "> {tip} 코드 재 사용률을 높이려면 콘솔 명령어을 가볍게 유지하고 작업을 수행하기 위해 애플리케이션 서비스를 불러오도록 하는 것이 좋습니다. 위의 예제에서 우리는 이메일을 보내는 \"중요한 작업\"을 수행하기 위해 서비스 클래스를 주입 받았습니다.",
            "timestamp": 1634350077,
            "email": null,
            "default": null
        },
        {
            "text": "> {tip} 코드 재 사용률을 높이려면 콘솔 명령어을 가볍게 유지하고 작업을 수행하기 위해 애플리케이션 서비스를 불러오도록 하는 것이 좋습니다. 위의 예제에서 우리는 이메일을 보내는 \"중요한 작업\"을 수행하기 위해 서비스 클래스를 주입 받았습니다.",
            "timestamp": 1634350068,
            "email": null,
            "default": null
        }
    ]
}