{
    "language": "en",
    "text": "For most projects (and to take advantage of Tailwind’s customization features), you’ll want to install Tailwind and its peer-dependencies via npm.",
    "key": "6f\\1e\\2e\\f0\\b9\\26\\7a\\ed",
    "ko": [
        {
            "text": "대부분의 프로젝트에서 Tailwind의 사용자 지정 기능을 활용하려면 npm을 통해 Tailwind와 해당 피어 종속성을 설치하고 싶을 것입니다.",
            "timestamp": 1633757719,
            "email": null,
            "default": null
        }
    ]
}